add jmeter pipeline with k8s

diff --git a/backend/catalogue-service/Jenkinsfile.k8s.local b/backend/catalogue-service/Jenkinsfile.k8s.local
--- a/backend/catalogue-service/Jenkinsfile.k8s.local
+++ b/backend/catalogue-service/Jenkinsfile.k8s.local
@@ -85,6 +85,60 @@ spec:
             }
         }
 
+        stage('Wait for Deployments Ready') {
+            steps {
+                container('kubectl') {
+                    sh '''
+                    kubectl rollout status deployment kafka -n catalogue-service
+                    kubectl rollout status deployment redis -n catalogue-service
+                    kubectl rollout status deployment catalogue-service -n catalogue-service
+                    '''
+                }
+            }
+        }
+
+        stage('Wait for App Health') {
+            steps {
+                container('kubectl') {
+                    sh '''
+                    timeout=60
+                    elapsed=0
+
+                    until kubectl run curl-test --rm -i --restart=Never --image=curlimages/curl:latest -n catalogue-service -- \
+                      curl -s http://catalogue-service:8081/actuator/health | grep '"status":"UP"' > /dev/null; do
+
+                        if [ $elapsed -ge $timeout ]; then
+                            echo "App failed to become healthy"
+                            exit 1
+                        fi
+
+                        sleep 3
+                        elapsed=$((elapsed+3))
+                    done
+                    '''
+                }
+            }
+        }
+
+        stage('Performance Test (JMeter)') {
+            steps {
+                container('kubectl') {
+                    sh '''
+                    kubectl cp backend/catalogue-service/jmeter/catalogue-docker-test.jmx catalogue-service/jmeter:/catalogue-docker-test.jmx
+
+                    kubectl exec jmeter -n catalogue-service -- \
+                    jmeter -n -t /catalogue-docker-test.jmx -l /results.jtl -JtestType=veryhigh
+
+                    kubectl exec jmeter -n catalogue-service -- \
+                    jmeter -g /results.jtl -o /report
+
+                    kubectl cp catalogue-service/jmeter:/results.jtl backend/catalogue-service/jmeter/results.jtl
+                    kubectl cp catalogue-service/jmeter:/report backend/catalogue-service/jmeter/report-${BUILD_NUMBER}
+                    '''
+                }
+            }
+        }
+
         stage('Verify') {
             steps {
                 container('kubectl') {
