Updaetd jenkins settings

diff --git a/backend/catalogue-service/Jenkinsfile b/backend/catalogue-service/Jenkinsfile
--- a/backend/catalogue-service/Jenkinsfile
+++ b/backend/catalogue-service/Jenkinsfile
@@ -25,12 +25,39 @@ pipeline {
             }
         }
 
+        //PRODUCTION (Needed so that app can boot first)
+        stage('Wait for Service Health') {
+            steps {
+                sh '''
+                echo "Waiting for service to be ready..."
+
+                timeout=60
+                interval=3
+                elapsed=0
+
+                while [ $elapsed -lt $timeout ]; do
+                  if curl -s http://host.docker.internal:8081/actuator/health | grep '"status":"UP"' > /dev/null; then
+                    echo "Service is UP"
+                    exit 0
+                  fi
+
+                  echo "Still starting..."
+                  sleep $interval
+                  elapsed=$((elapsed + interval))
+                done
+
+                echo "Service failed to start in time"
+                exit 1
+                '''
+            }
+        }
+
         stage('Performance Test (JMeter)') {
             steps {
                 sh '''
                 cd backend/catalogue-service/jmeter
 
-                # CLEAN OLD FILES (CRITICAL)
+                # CLEAN OLD FILES
                 rm -rf report results.jtl jmeter.log || true
 
                 docker run --rm \
